run:
  preprocessing:
    source: 'hifiasm'
    genomes: 
      - 'arab'
      - 'chicken'
  generate_baseline:
    source: 'hifiasm'
    genomes:
      - 'arab'
      - 'chicken'
  postprocessing:
    genomes:
      - 'arab'
      - 'chicken'

postprocessing:
  walk_valid_p: 0.0025
  use_telomere_info : true
  dfs_penalty: null # None, ol_len or ol_sim
  walk_var: 'telomere' # default or telomere

misc:
  paths:
    model: '/home/stumanuel/GAP/misc/default_best.pt'
    seqtk: '/home/stumanuel/GitHub/seqtk/seqtk'
    minigraph: '/home/stumanuel/GitHub/minigraph/minigraph'
    paftools: '/home/stumanuel/GitHub/minimap2/misc/paftools.js'

genome_info:
  arab:
    telo_motifs:
      - 'TTTAGGG'
      - 'CCCTAAA'
    paths:
      ec_reads: '/mnt/sod2-project/csb4/wgs/lovro_interns/joshua/GAP/hifiasm/arab/arab.ec.fa'
      gfa: '/mnt/sod2-project/csb4/wgs/lovro_interns/joshua/GAP/hifiasm/arab/arab.bp.p_ctg.gfa'
      baseline: '/mnt/sod2-project/csb4/wgs/lovro_interns/joshua/GAP/baseline/hifiasm/arab/'
      paf: '/mnt/sod2-project/csb4/wgs/lovro_interns/joshua/GAP/hifiasm/arab/arab.ovlp.paf'
      paf_processed: '/mnt/sod2-project/csb4/wgs/lovro_interns/joshua/GAP/supp/hifiasm/arab/arab_paf_data.pkl'
      ref: '/mnt/sod2-project/csb4/wgs/lovro/gnnome_assembly/references/arabidopsis/latest/GWHBDNP00000000.1.genome.fasta'
      save: '/mnt/sod2-project/csb4/wgs/lovro_interns/joshua/GAP/res/hifiasm/arab/'
      walks: '/mnt/sod2-project/csb4/wgs/lovro_interns/joshua/GAP/baseline/hifiasm/arab/walks.pkl' # Ensure this aligns with baseline
  chicken:
    telo_motifs:
      - 'TTAGGG'
      - 'CCCTAA'
    paths:
      ec_reads: '/mnt/sod2-project/csb4/wgs/lovro_interns/joshua/GAP/hifiasm/chicken/chicken.ec.fa'
      gfa: '/mnt/sod2-project/csb4/wgs/lovro_interns/joshua/GAP/hifiasm/chicken/chicken.bp.p_ctg.gfa'
      baseline: '/mnt/sod2-project/csb4/wgs/lovro_interns/joshua/GAP/baseline/hifiasm/chicken/'
      paf: '/mnt/sod2-project/csb4/wgs/lovro_interns/joshua/GAP/hifiasm/chicken/chicken.ovlp.paf'
      paf_processed: '/mnt/sod2-project/csb4/wgs/lovro_interns/joshua/GAP/supp/hifiasm/chicken/chicken_paf_data.pkl'
      ref: '/mnt/sod2-project/csb4/wgs/lovro/gnnome_assembly/references/bGalGal1/maternal/GCF_016699485.2_bGalGal1.mat.broiler.GRCg7b_genomic.fna'
      save: '/mnt/sod2-project/csb4/wgs/lovro_interns/joshua/GAP/res/hifiasm/chicken/'
      walks: '/mnt/sod2-project/csb4/wgs/lovro_interns/joshua/GAP/baseline/hifiasm/chicken/walks.pkl' # Ensure this aligns with baseline
  chm13:
    telo_motifs:
      - 'TTAGGG'
      - 'CCCTAA'
    paths:
      ec_reads: '/mnt/sod2-project/csb4/wgs/lovro_interns/joshua/GAP/hifiasm/chm13/chm13.ec.fa'
      gfa: '/mnt/sod2-project/csb4/wgs/lovro_interns/joshua/GAP/hifiasm/chm13/chm13.bp.p_ctg.gfa'
      baseline: '/mnt/sod2-project/csb4/wgs/lovro_interns/joshua/GAP/baseline/hifiasm/chm13/'
      paf: '/mnt/sod2-project/csb4/wgs/lovro_interns/joshua/GAP/hifiasm/chm13/chm13.ovlp.paf'
      paf_processed: '/mnt/sod2-project/csb4/wgs/lovro_interns/joshua/GAP/supp/hifiasm/chm13/chm13_paf_data.pkl'
      ref: '/mnt/sod2-project/csb4/wgs/martin/genome_references/chm13_v11/chm13_full_v1_1.fasta'
      save: '/mnt/sod2-project/csb4/wgs/lovro_interns/joshua/GAP/res/hifiasm/chm13/'
      walks: '/mnt/sod2-project/csb4/wgs/lovro_interns/joshua/GAP/baseline/hifiasm/chm13/walks.pkl' # Ensure this aligns with baseline
  maize:
    telo_motifs:
      - 'TTTAGGG'
      - 'CCCTAAA'
    paths:
      ec_reads: '/mnt/sod2-project/csb4/wgs/lovro_interns/joshua/GAP/hifiasm/maize/maize.ec.fa'
      gfa: '/mnt/sod2-project/csb4/wgs/lovro_interns/joshua/GAP/hifiasm/maize/maize.bp.p_ctg.gfa'
      baseline: '/mnt/sod2-project/csb4/wgs/lovro_interns/joshua/GAP/baseline/hifiasm/maize/'
      paf: '/mnt/sod2-project/csb4/wgs/lovro_interns/joshua/GAP/hifiasm/maize/maize.ovlp.paf'
      paf_processed: '/mnt/sod2-project/csb4/wgs/lovro_interns/joshua/GAP/supp/hifiasm/maize/maize_paf_data.pkl'
      ref: '/mnt/sod2-project/csb4/wgs/lovro/gnnome_assembly/references/zmays_Mo17/zmays_Mo17.fasta'
      save: '/mnt/sod2-project/csb4/wgs/lovro_interns/joshua/GAP/res/hifiasm/maize/'
      walks: '/mnt/sod2-project/csb4/wgs/lovro_interns/joshua/GAP/baseline/hifiasm/maize/walks.pkl' # Ensure this aligns with baseline

# GNNome's model configs for decoding. Recommended not to touch these.
gnnome:
  training:
    seed: 1
    node_features: 3
    edge_features: 2
    hidden_features: 64
    hidden_edge_features: 16
    hidden_edge_scores: 64
    num_gnn_layers: 8
    batch_norm: True
    dropout: 0.2  
    
  decoding:
    num_decoding_paths: 100
    load_checkpoint: True
    num_threads: 32
    len_threshold: 10
